FROM node:carbon

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
#COPY package.json .
# For npm@5 or later, copy package-lock.json as well
# COPY package.json package-lock.json ./

# If you are building your code for production

# Bundle app source
# COPY . .

# RUN yarn
# RUN yarn build

EXPOSE 1337


#CMD [ "yarn", "start"]
