export const AUTH_REQUEST = 'AUTH_REQUEST';

export const AUTH_PHONE_REQUEST = 'AUTH_PHONE_REQUEST';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';

export const AUTH_ERROR = 'AUTH_ERROR';

export const AUTH_PROFILE_REQUEST = 'AUTH_PROFILE_REQUEST';

export const AUTH_PROFILE_SUCCESS = 'AUTH_PROFILE_SUCCESS';

export const AUTH_PROFILE_ERROR = 'AUTH_PROFILE_ERROR';

export const AUTH_PROFILE_EXIT = 'AUTH_PROFILE_EXIT';

export const AUTH_REGISTER_REQUEST = 'AUTH_REGISTER_REQUEST';

export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';

export const AUTH_REGISTER_ERROR = 'AUTH_REGISTER_ERROR';

export const AUTH_RECOVERY_REQUEST = 'AUTH_RECOVERY_REQUEST';

export const AUTH_RECOVERY_SUCCESS = 'AUTH_RECOVERY_SUCCESS';

export const AUTH_RECOVERY_ERROR = 'AUTH_RECOVERY_ERROR';

export const AUTH_PHONE_LOGIN_REQUEST = 'AUTH_PHONE_LOGIN_REQUEST';

export const AUTH_PHONE_LOGIN_SUCCESS = 'AUTH_PHONE_LOGIN_SUCCESS';

export const AUTH_PHONE_LOGIN_ERROR = 'AUTH_PHONE_LOGIN_ERROR';

export const AUTH_ADD_PHONE = 'AUTH_ADD_PHONE';
